## note key is “additional-ca-1” so you called the object - name and then the key! 
#additional-ca-1.yaml
apiVersion: v1
data:
  additional-ca-1: TFMwdExTMUNSGlSzZ3Jaa...VVNVWkpRMEMwdExTMHRDZz09
kind: Secret
metadata:
  name: VKS-CLUSTER-trusted-ca-secret
  namespace: MYVKSCLUSTERNAMESPACE
type: Opaque
